// <auto-generated />
namespace TicketApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Youhavetohaverelationsthisway : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Youhavetohaverelationsthisway));
        
        string IMigrationMetadata.Id
        {
            get { return "201610161728065_You have to have relations this way"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
